// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using TaskApplication.Models;

namespace TaskApplication.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20180123180247_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TaskApplication.Models.Emploees", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();
                    b.Property<string>("F_NAME");

                    b.Property<string>("L_NAME");

                    b.Property<bool>("FIX_PAYMENT");

                    b.Property<int>("COUNT_DAYS");

                    b.Property<int>("COUNT_HOUR");

                    b.Property<int>("RATE");

                    b.HasKey("ID");

                    b.ToTable("Emploees");
                });
#pragma warning restore 612, 618
        }
    }
}
